# Generated by Django 3.2.8 on 2021-10-07 14:59

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('deeplearning', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='upload_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
