# Generated by Django 3.2.8 on 2021-10-12 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deeplearning', '0005_log'),
    ]

    operations = [
        migrations.AddField(
            model_name='log',
            name='username',
            field=models.CharField(default='wonbeom', max_length=30),
            preserve_default=False,
        ),
    ]
