channels:
- conda-forge
dependencies:
- python=3.6.2
- pytorch
- torchvision
- cudatoolkit=10.1
- pip:
  - azureml-defaults
  - future==0.17.1
  - pillow
  - matplotlib>=3.2.2
  - numpy>=1.18.5
  - opencv-python>=4.1.2
  - Pillow>=7.1.2
  - PyYAML>=5.3.1
  - scipy>=1.4.1
  - torch>=1.7.0
  - torchvision>=0.8.1
  - tqdm>=4.41.0
  - tensorboard>=2.4.1
#   - wandb
  - pandas
  - seaborn>=0.11.0
  - thop  # FLOPs computation
  - googledrivedownloader==0.4