# Generated by Django 3.2.8 on 2021-10-11 01:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deeplearning', '0003_trainedmodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='trainedmodel',
            name='matrix',
            field=models.FloatField(default=0.60714),
            preserve_default=False,
        ),
    ]
