# Generated by Django 3.2.8 on 2021-10-14 13:30

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('deeplearning', '0006_log_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='log',
            name='create_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
